-- MySQL Script generated by MySQL Workbench
-- Sat Jan 22 14:43:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema library_management_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library_management_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library_management_system` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `library_management_system` ;

-- -----------------------------------------------------
-- Table `library_management_system`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_management_system`.`books` (
  `bid` INT(11) NOT NULL AUTO_INCREMENT,
  `book_isbn` VARCHAR(40) NOT NULL,
  `book_name` VARCHAR(50) NOT NULL,
  `book_publisher` VARCHAR(50) NOT NULL,
  `book_edition` VARCHAR(50) NOT NULL,
  `book_genre` VARCHAR(20) NOT NULL,
  `book_price` INT(11) NOT NULL,
  `book_pages` INT(11) NOT NULL,
  PRIMARY KEY (`bid`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library_management_system`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_management_system`.`users` (
  `UID` INT(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(30) NOT NULL,
  `PASSWORD` VARCHAR(30) NOT NULL,
  `USER_TYPE` INT(11) NOT NULL,
  PRIMARY KEY (`UID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library_management_system`.`issued_books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_management_system`.`issued_books` (
  `IID` INT(11) NOT NULL AUTO_INCREMENT,
  `UID` INT(11) NOT NULL,
  `BID` INT(11) NOT NULL,
  `ISSUED_DATE` VARCHAR(20) NOT NULL,
  `PERIOD` INT(11) NOT NULL,
  PRIMARY KEY (`IID`),
  INDEX `UID` (`UID` ASC) VISIBLE,
  INDEX `BID` (`BID` ASC) VISIBLE,
  CONSTRAINT `issued_books_ibfk_1`
    FOREIGN KEY (`UID`)
    REFERENCES `library_management_system`.`users` (`UID`),
  CONSTRAINT `issued_books_ibfk_2`
    FOREIGN KEY (`BID`)
    REFERENCES `library_management_system`.`books` (`bid`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library_management_system`.`returned_books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_management_system`.`returned_books` (
  `rid` INT(11) NOT NULL AUTO_INCREMENT,
  `bid` INT(11) NOT NULL,
  `uid` INT(11) NOT NULL,
  `return_date` VARCHAR(50) NOT NULL,
  `fine` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`rid`),
  INDEX `uid` (`uid` ASC) VISIBLE,
  INDEX `bid` (`bid` ASC) VISIBLE,
  CONSTRAINT `returned_books_ibfk_1`
    FOREIGN KEY (`uid`)
    REFERENCES `library_management_system`.`users` (`UID`),
  CONSTRAINT `returned_books_ibfk_2`
    FOREIGN KEY (`bid`)
    REFERENCES `library_management_system`.`books` (`bid`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
